
-- CREATE DATABASE IF NOT exists concredito_test;

-- USE concredito_test;

CREATE TABLE IF NOT exists prospectos (
	id bigint generated by default as identity, 
	calle varchar(25) not null, 
	codigo_postal varchar(255), 
	colonia varchar(25) not null, 
	nombre varchar(25) not null, 
	numero integer not null, 
	observacion varchar(255), 
	primer_apellido varchar(25) not null, 
	rfc varchar(18), ruta_docs varchar(255), 
	segundo_apellido varchar(255), 
	status varchar(255), 
	telefono varchar(255), 
	primary key (id)
);